### ISSUE TITLE
api key missing

### ISSUE THREAD

**Issue by wangtao520** [jeasonlzy/okhttp-OkGo#130]
http://apis.baidu.com/showapi_open_bus/channel_news/search_news?commonParamsKey1=commonParamsValue1&commonParamsKey2=%E8%BF%99%E9%87%8C%E6%94%AF%E6%8C%81%E4%B8%AD%E6%96%87%E5%8F%82%E6%95%B0&channelName=%E5%9B%BD%E5%86%85%E6%9C%80%E6%96%B0&page=1

java.lang.NullPointerException: Attempt to read from field 'int com.lzy.demo.model.NewsModel$PageBean.currentPage' on a null object reference
                                                                  at com.lzy.demo.cache.NewsTabFragment$1.onSuccess(NewsTabFragment.java:91)
                                                                  at com.lzy.demo.cache.NewsTabFragment$1.onCacheSuccess(NewsTabFragment.java:101)
                                                                  at com.lzy.demo.cache.NewsTabFragment$1.onCacheSuccess(NewsTabFragment.java:87)
                                                                  at com.lzy.okgo.adapter.CacheCall$3.run(CacheCall.java:242)

这个请求地址打不开

**Comment by jeasonlzy** [comment]
这是我用的第三方的api接口，可能把我的接口给封了，我修复一下。。
