### ISSUE TITLE
OutOfMemoryError when logForResponse

### ISSUE THREAD

**Issue by wankey** [jeasonlzy/okhttp-OkGo#159]
`java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                     at com.lzy.okserver.task.PriorityAsyncTask$2.done(PriorityAsyncTask.java:81)
                                                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                     at com.lzy.okserver.task.PriorityRunnable.run(PriorityRunnable.java:20)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                                  Caused by: java.lang.OutOfMemoryError: Failed to allocate a 151340226 byte allocation with 16777216 free bytes and 123MB until OOM
                                                                                     at java.lang.StringFactory.newStringFromChars(Native Method)
                                                                                     at java.lang.AbstractStringBuilder.toString(AbstractStringBuilder.java:629)
                                                                                     at java.lang.StringBuilder.toString(StringBuilder.java:663)
                                                                                     at com.lzy.okgo.interceptor.HttpLoggingInterceptor.logForResponse(HttpLoggingInterceptor.java:138)
                                                                                     at com.lzy.okgo.interceptor.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:84)
                                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                                                     at okhttp3.RealCall.execute(RealCall.java:60)
                                                                                     at com.lzy.okgo.request.BaseRequest.execute(BaseRequest.java:379)
                                                                                     at com.lzy.okserver.download.DownloadTask.doInBackground(DownloadTask.java:126)
                                                                                     at com.lzy.okserver.download.DownloadTask.doInBackground(DownloadTask.java:31)
                                                                                     at com.lzy.okserver.task.PriorityAsyncTask$1.call(PriorityAsyncTask.java:69)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at com.lzy.okserver.task.PriorityRunnable.run(PriorityRunnable.java:20) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                     at java.lang.Thread.run(Thread.java:818) `

**Comment by jeasonlzy** [comment]
原因是你返回的数据是文件，但是content-type 返回的是文本类型，与正真的数据格式不匹配，服务端要修正content-type类型，或者你把okgo 的调试log关闭。
