### ISSUE TITLE
Upload Pictures Exception

### ISSUE THREAD

**Issue by dabingrunning** [jeasonlzy/okhttp-OkGo#260]
上传多张图片时，图片上传耗时很久，出现下列异常

java.io.EOFException
    at okio.RealBufferedSource.require(RealBufferedSource.java:59)
    at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:284)
    at okhttp3.internal.http.Http1xStream$ChunkedSource.readChunkSize(Http1xStream.java:437)
    at okhttp3.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:418)
    at okio.Buffer.writeAll(Buffer.java:993)
    at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:106)
    at okhttp3.ResponseBody.bytes(ResponseBody.java:128)
    at okhttp3.ResponseBody.string(ResponseBody.java:154)
    at com.lzy.okgo.interceptor.HttpLoggingInterceptor.logForResponse(HttpLoggingInterceptor.java:137)
    at com.lzy.okgo.interceptor.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:84)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
    at okhttp3.RealCall.access$100(RealCall.java:33)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
D HTTP
java.lang.IllegalStateException: closed
    at okhttp3.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:414)
    at okio.Buffer.writeAll(Buffer.java:993)
    at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:106)
    at okhttp3.ResponseBody.bytes(ResponseBody.java:128)
    at okhttp3.ResponseBody.string(ResponseBody.java:154)
    at com.lzy.okgo.convert.StringConvert.convertSuccess(StringConvert.java:26)
    at com.lzy.okgo.callback.StringCallback.convertSuccess(StringCallback.java:20)
    at com.lzy.okgo.callback.StringCallback.convertSuccess(StringCallback.java:16)
    at com.lzy.okgo.adapter.CacheCall.parseResponse(CacheCall.java:269)
    at com.lzy.okgo.adapter.CacheCall.access$600(CacheCall.java:34)
    at com.lzy.okgo.adapter.CacheCall$1.onResponse(CacheCall.java:160)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)

**Comment by jeasonlzy** [comment]
可能是流断开了，或者网络异常了。
