### ISSUE TITLE
app点击强大的缓存实例那一栏，闪退，报错如下

### ISSUE THREAD

**Issue by StriveCheng** [jeasonlzy/okhttp-OkGo#270]
05-24 17:18:20.556 14237-14237/com.lzy.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: com.lzy.demo, PID: 14237
                                                              java.lang.NullPointerException: Attempt to read from field 'com.lzy.demo.model.NewsModel$PageBean com.lzy.demo.model.NewsModel.pagebean' on a null object reference
                                                                  at com.lzy.demo.cache.NewsTabFragment$1.onSuccess(NewsTabFragment.java:87)
                                                                  at com.lzy.demo.cache.NewsTabFragment$1.onCacheSuccess(NewsTabFragment.java:98)
                                                                  at com.lzy.demo.cache.NewsTabFragment$1.onCacheSuccess(NewsTabFragment.java:83)
                                                                  at com.lzy.okgo.adapter.CacheCall$3.run(CacheCall.java:242)
                                                                  at android.os.Handler.handleCallback(Handler.java:815)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                  at android.os.Looper.loop(Looper.java:194)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5869)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by jeasonlzy** [comment]
这个是服务器api接口下架了，okgo升级3.0，已经换了个接口，欢迎使用。。
