### ISSUE TITLE
downloadManager多任务下载，总是出现：文件读写异常

### ISSUE THREAD

**Issue by liajt** [jeasonlzy/okhttp-OkGo#275]
java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
	at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:552)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:516)
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
	at okio.RealBufferedSource.read(RealBufferedSource.java:45)
	at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:377)
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:409)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:304)
	at com.lzy.okserver.download.DownloadTask.download(DownloadTask.java:223)
	at com.lzy.okserver.download.DownloadTask.doInBackground(DownloadTask.java:176)
	at com.lzy.okserver.download.DownloadTask.doInBackground(DownloadTask.java:30)
	at com.lzy.okserver.task.PriorityAsyncTask$1.call(PriorityAsyncTask.java:69)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at com.lzy.okserver.task.PriorityRunnable.run(PriorityRunnable.java:20)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:856)
Caused by: libcore.io.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
	at libcore.io.Posix.recvfromBytes(Native Method)
	at libcore.io.Posix.recvfrom(Posix.java:136)
	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:513)
	... 18 more

下载地址是：http://115.29.99.117:8080/gnamp_work/1411717214/contents/files/2015-02/000054E1CFD91F00

**Comment by jeasonlzy** [comment]
主要服务端可能关闭了链接。。详细需要后台配置下。。
