### ISSUE TITLE
每次初始化的时候会有异常

### ISSUE THREAD

**Issue by pdog18** [jeasonlzy/okhttp-OkGo#279]
D/PersistentCookieStore: ClassNotFoundException in decodeCookie
                                                                                java.lang.ClassNotFoundException: com.lzy.a.e.a.d
                                                                                    at java.lang.Class.classForName(Native Method)
                                                                                    at java.lang.Class.forName(Class.java:324)
                                                                                    at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:2258)
                                                                                    at java.io.ObjectInputStream.readNewClassDesc(ObjectInputStream.java:1641)
                                                                                    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:657)
                                                                                    at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1782)
                                                                                    at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
                                                                                    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
                                                                                    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
                                                                                    at com.lzy.okgo.cookie.store.PersistentCookieStore.decodeCookie(PersistentCookieStore.java:237)
                                                                                    at com.lzy.okgo.cookie.store.PersistentCookieStore.<init>(PersistentCookieStore.java:59)

我在debug下 一没有开混淆啊

初始化代码

        OkGo.init(this);
        OkGo.getInstance()
                .debug("Okgo", Level.INFO, Switchs.OKGO_LOG_ENABLE)
                .setConnectTimeout(10000)               //全局的连接超时时间 （服务器访问超时）
                .setReadTimeOut(10000)                  //全局的读取超时时间
                .setWriteTimeOut(10000)                 //全局的写入超时时间
                .setRetryCount(1)                      //全局的重试次数
                .setCacheMode(CacheMode.FIRST_CACHE_THEN_REQUEST)  //先使用缓存，不管是否存在，仍然请求网络
//                .setCookieStore(new MemoryCookieStore())        //内存缓存
                .setCookieStore(new PersistentCookieStore())  //持久化缓存
                .setCertificates();    //信任所有https证书

有异常的代码         
       .setCacheMode(CacheMode.FIRST_CACHE_THEN_REQUEST)  //先使用缓存，不管是否存在，仍然请求网络

**Comment by jeasonlzy** [comment]
异常看起来就是混淆的问题，把文档下面的混淆规则添加到你的混淆文件中，再试试。

**Comment by pdog18** [comment]
@jeasonlzy 谢谢回复，混淆规则我是添加（确认过）。而且我debug模式也没有打开混淆功能。
但是奇怪的是我另外开个项目使用的时候却不会有这个报错，我已经混乱了
