### ISSUE TITLE
非主线程downloadmanager报错

### ISSUE THREAD

**Issue by liajt** [jeasonlzy/okhttp-OkGo#281]
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                               at android.os.Handler.<init>(Handler.java:197)
                                                               at android.os.Handler.<init>(Handler.java:111)
                                                               at com.lzy.okserver.download.DownloadUIHandler.<init>(DownloadUIHandler.java:18)
                                                               at com.lzy.okserver.download.DownloadManager.<init>(DownloadManager.java:58)
                                                               at com.lzy.okserver.download.DownloadManager.getInstance(DownloadManager.java:49)
                                                               at com.lzy.okserver.download.DownloadService.getDownloadManager(DownloadService.java:35)
                                                               at com.led.player.utils.UpdateUtils$1.run(UpdateUtils.java:73)
                                                               at java.lang.Thread.run(Thread.java:856)

**Comment by jeasonlzy** [comment]
这个在okgo的3.0版本修复了，欢迎使用。。
