### ISSUE TITLE
下载文件出现异常

### ISSUE THREAD

**Issue by xiaobaiAndroid** [jeasonlzy/okhttp-OkGo#291]
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.lzy.okgo.cache.CacheMode.ordinal()' on a null object reference
                                                                at com.lzy.okgo.adapter.CacheCall.preparePolicy(CacheCall.java:66)
                                                                at com.lzy.okgo.adapter.CacheCall.<init>(CacheCall.java:46)
                                                                at com.lzy.okgo.request.Request.adapt(Request.java:357)
                                                                at com.lzy.okgo.request.Request.execute(Request.java:391)
                                                                at com.hxs.cc.main.DownloadService.onHandleIntent(DownloadService.java:67)
                                                                at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
                                                                at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                at android.os.Looper.loop(Looper.java:156)
                                                                at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by jeasonlzy** [comment]
已解决，会发布小版本修复。。

**Comment by budingts** [comment]
什么时候修复啊，我也遇到这个问题了

**Comment by jeasonlzy** [comment]
明后天的样子。。
