### ISSUE TITLE
okgo2.1.4版本出现FATAL EXCEPTION: RxIoScheduler-2错误

### ISSUE THREAD

**Issue by ccddy** [jeasonlzy/okhttp-OkGo#320]
FATAL EXCEPTION: RxIoScheduler-2
                                                   Process: com.xxx.xxx, PID: 10426
                                                   java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                       at rx.internal.schedulers.ScheduledAction.run(TbsSdkJava:59)
                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                       at java.lang.Thread.run(Thread.java:818)
                                                    Caused by: java.lang.OutOfMemoryError: Failed to allocate a 139126 byte allocation with 4064 free bytes and 3KB until OOM
                                                       at java.lang.StringFactory.newStringFromChars(Native Method)
                                                       at java.lang.StringFactory.newStringFromChars(StringFactory.java:218)
                                                       at java.lang.StringFactory.newStringFromBytes(StringFactory.java:203)
                                                       at java.lang.StringFactory.newStringFromBytes(StringFactory.java:63)
                                                       at okhttp3.ResponseBody.string(TbsSdkJava:154)
                                                       at com.lzy.okgo.convert.StringConvert.convertSuccess(TbsSdkJava:26)
                                                       at com.lzy.okgo.convert.StringConvert.convertSuccess(TbsSdkJava:14)
                                                       at com.lzy.okgo.adapter.CacheCall.parseResponse(TbsSdkJava:269)
                                                       at com.lzy.okgo.adapter.CacheCall.execute(TbsSdkJava:264)
                                                       at com.lzy.okrx.RxAdapter$RequestArbiter.request(TbsSdkJava:86)
                                                       at rx.internal.operators.ce$1$1$1.request(TbsSdkJava:80)
                                                       at rx.l.setProducer(TbsSdkJava:211)
                                                       at rx.internal.operators.aa$a.setProducer(TbsSdkJava:102)
                                                       at rx.l.setProducer(TbsSdkJava:205)
                                                       at rx.internal.operators.ce$1$1.setProducer(TbsSdkJava:76)
                                                       at com.lzy.okrx.RxAdapter$CallOnSubscribe.call(TbsSdkJava:65)
                                                       at com.lzy.okrx.RxAdapter$CallOnSubscribe.call(TbsSdkJava:50)
                                                       at rx.e.a(TbsSdkJava:10142)
                                                       at rx.internal.operators.ce$1.a(TbsSdkJava:94)
                                                       at rx.internal.schedulers.a$b$1.a(TbsSdkJava:230)
                                                       at rx.internal.schedulers.ScheduledAction.run(TbsSdkJava:55)
                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154) 
                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by jeasonlzy** [comment]
核心原因是  Caused by: java.lang.OutOfMemoryError: Failed to allocate a 139126 byte allocation with 4064 free bytes and 3KB until OOM

导致这个原因的是  at com.lzy.okgo.convert.StringConvert.convertSuccess(TbsSdkJava:26)

所以检查你把什么转成字符串了。。导致了 OOM。。
