### ISSUE TITLE
OkDownload下载过程中出现： breakpoint file does not exist!

### ISSUE THREAD

**Issue by liajt** [jeasonlzy/okhttp-OkGo#321]
下载出错： realUrl:http://115.29.99.117:8080/gnamp_work/1411717214/contents/files/2015-04/0000551BA08FF400
com.lzy.okgo.exception.OkGoException: breakpoint file does not exist!
                                                                     at com.lzy.okserver.download.DownloadTask.run(DownloadTask.java:215)
                                                                     at com.lzy.okserver.task.PriorityRunnable.run(PriorityRunnable.java:35)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                     at java.lang.Thread.run(Thread.java:856)

**Comment by jeasonlzy** [comment]
那是因为你把断点文件删掉了，下载出错。重新下载就可以了。

DownloadTask#restart()

**Comment by liajt** [comment]
OkDownload的使用文档有没有完善出来啊，我没有删除断点文件啊

**Comment by jeasonlzy** [comment]
总之这是个很正常的问题，重新下载就可以了。并不会影响什么。。

文档后面再补吧，主要看demo就够了。
