### ISSUE TITLE
新版Demo 点击okDownload 中已完成任务crash

### ISSUE THREAD

**Issue by buildcodeworld** [jeasonlzy/okhttp-OkGo#323]

**Comment by buildcodeworld** [comment]
Process: com.lzy.demo, PID: 24367
                                                              java.lang.NullPointerException
                                                                  at java.io.File.<init>(File.java:262)
                                                                  at com.lzy.demo.okdownload.DownloadAdapter$ViewHolder.refresh(DownloadAdapter.java:178)
                                                                  at com.lzy.demo.okdownload.DownloadAdapter.onBindViewHolder(DownloadAdapter.java:106)
                                                                  at com.lzy.demo.okdownload.DownloadAdapter.onBindViewHolder(DownloadAdapter.java:58)
                                                                  at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                  at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                  at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                  at android.view.View.layout(View.java:17529)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                  at android.view.View.layout(View.java:17529)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                  at android.view.View.layout(View.java:17529)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                  at android.view.View.layout(View.java:17529)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                  at android.view.View.layout(View.java:17529)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                  at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                  at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                  at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                  at android.view.View.layout(View.java:17529)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                  at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                  at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                  at com.android.internal.policy.DecorView.onLayout(DecorView.java:724)
                                                                  at android.view.View.layout(View.java:17529)
                                                                  at android.view.ViewGroup.layout(ViewGroup.java:5612)
                                                                  at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2387)
                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2114)
                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1291)
                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6362)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:685)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
                                                                  at android.os.Handler.handleCallback(Handler.java:754)
06-21 14:54:20.494 24367-24367/com.lzy.demo E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:160)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6200)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)
