### ISSUE TITLE
OkDownload频繁pauseAll()和start()报错：Cannot perform this operation because there is no current transaction

### ISSUE THREAD

**Issue by liajt** [jeasonlzy/okhttp-OkGo#324]
06-21 15:29:34.460 8562-8562/com.led.player I/MyDownLoadService: 下载进度： fraction:0.0 DownloadLength:0 TotalLength:-1 speed:0 FileName:（3）箴言.jpg_
06-21 15:29:34.470 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.470 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.470 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.470 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.490 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.490 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.500 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.500 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.500 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.500 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.500 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.500 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.510 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.510 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.520 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.520 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.520 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.530 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.530 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.540 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.540 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.540 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.540 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.550 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.550 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.550 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.550 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.560 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.560 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.560 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.560 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.570 8562-8565/com.led.player D/dalvikvm: GC_CONCURRENT freed 911K, 67% free 6601K/19828K, paused 5ms+6ms, total 72ms
06-21 15:29:34.590 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.600 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.600 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.600 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.600 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.600 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.600 8562-18047/com.led.player W/OkGo: only the task with status WAITING(1) or LOADING(2) can pause, current status is 3
06-21 15:29:34.610 8562-18022/com.led.player D/CrashReport: [Database] insert t_cr success.
06-21 15:29:34.620 8562-18022/com.led.player D/CrashReport: insert t_cr success!
06-21 15:29:34.620 8562-18022/com.led.player D/CrashReport: update state size 1
06-21 15:29:34.630 8562-11359/com.led.player E/CrashReport: sys default last handle start!
06-21 15:29:34.660 8562-8562/com.led.player I/MyDownLoadService: 下载进度： fraction:0.0 DownloadLength:0 TotalLength:-1 speed:0 FileName:故驿广场舞 (2).mp4_
06-21 15:29:34.690 8562-8562/com.led.player I/MyDownLoadService: 下载进度： fraction:0.0 DownloadLength:0 TotalLength:-1 speed:0 FileName:Koala.jpg_
06-21 15:29:34.750 8562-8562/com.led.player I/MyDownLoadService: 下载进度： fraction:0.0 DownloadLength:0 TotalLength:-1 speed:0 FileName:故驿广场舞 (3).mp4_
06-21 15:29:34.760 8562-11359/com.led.player E/AndroidRuntime: FATAL EXCEPTION: pool-15-thread-2
                                                               java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
                                                                   at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:915)
                                                                   at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:398)
                                                                   at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:522)
                                                                   at com.lzy.okgo.db.BaseDao.query(BaseDao.java:384)
                                                                   at com.lzy.okgo.db.BaseDao.query(BaseDao.java:356)
                                                                   at com.lzy.okgo.cookie.store.DBCookieStore.loadCookie(DBCookieStore.java:104)
                                                                   at com.lzy.okgo.cookie.CookieJarImpl.loadForRequest(CookieJarImpl.java:53)
                                                                   at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:84)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                   at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                   at com.lzy.okgo.interceptor.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:93)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                   at okhttp3.RealCall.execute(RealCall.java:69)
                                                                   at com.lzy.okgo.request.Request.execute(Request.java:383)
                                                                   at com.lzy.okserver.download.DownloadTask.run(DownloadTask.java:226)
                                                                   at com.lzy.okserver.task.PriorityRunnable.run(PriorityRunnable.java:35)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                   at java.lang.Thread.run(Thread.java:856)
06-21 15:29:34.790 8562-16871/com.led.player I/MyDownLoadService: 需要下载的文件：（2）箴言.jpg ,realUrl:http://115.29.99.117:8080/gnamp_work/1411717214/contents/files/2015-08/000055D5288EAA80
06-21 15:29:34.810 1367-17648/? D/Clock_Component: ----adjust ratio:1 ,precise_adjust_ratio:1, ref:14978164 sys:15041279 diff:-63115 diff-percent:-1 ----
06-21 15:29:34.830 8562-8562/com.led.player I/MyDownLoadService: 下载进度： fraction:0.0 DownloadLength:0 TotalLength:-1 speed:0 FileName:123.mp4_
06-21 15:29:34.870 2232-9191/system_process W/ActivityManager:   Force finishing activity com.led.player/.LedActivity
06-21 15:29:34.930 8562-8562/com.led.player D/CrashReport: >>> com.led.player.LedActivity onPaused <<<
06-21 15:29:34.970 8562-8562/com.led.player I/CrashReport-Native: Set native info: isAppForeground(false)

**Comment by liajt** [comment]
看日志是pauseAll()的时候，状态为3的暂停的状态停止的时候报错

**Comment by liajt** [comment]
endTransaction的时候报错

**Comment by jeasonlzy** [comment]
感谢你的反馈，目前已解决。。

**Comment by liajt** [comment]
谢谢
