### ISSUE TITLE
更新3.0.0版本后出现的问题

### ISSUE THREAD

**Issue by HelloClouds** [jeasonlzy/okhttp-OkGo#325]
<img width="765" alt="f8ea84d5-1d11-4363-bb16-b27362497c4c" src="https://user-images.githubusercontent.com/19909935/27376047-92dac8aa-56a3-11e7-8eec-632727d3ff2b.png">

**Comment by ypf168326** [comment]
问题同上
```
lifeceo.yika E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.ilifeceo.yika, PID: 15249
                                                                   java.lang.NoClassDefFoundError: okhttp3.MediaType
                                                                       at com.lzy.okgo.model.HttpParams.<clinit>(HttpParams.java:28)
                                                                       at com.ilifeceo.yika.biz.Http4GetConfig.execute(Http4GetConfig.java:35)
                                                                       at com.ilifeceo.yika.activity.LoginActivity.getConfig(LoginActivity.java:637)
                                                                       at com.ilifeceo.yika.activity.LoginActivity.onCreate(LoginActivity.java:161)
                                                                       at android.app.Activity.performCreate(Activity.java:5249)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2154)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2239)
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5047)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:807)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)
                                                                       at dalvik.system.NativeStart.main(Native Method)
```

**Comment by buildcodeworld** [comment]
你初始化了吗

**Comment by jeasonlzy** [comment]
关于 NoClassDefFoundError 看文档   [常见问题汇总](https://github.com/jeasonlzy/okhttp-OkGo/wiki/Q&A)
