### ISSUE TITLE
小米4，华为荣耀6报NoClassDefFoundError

### ISSUE THREAD

**Issue by ypf168326** [jeasonlzy/okhttp-OkGo#326]
使用版本2.1.4
```
6-10896/com.ilifeceo.yika W/dalvikvm: Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lcom/lzy/okgo/model/HttpParams;
06-22 09:25:51.815 10896-10896/com.ilifeceo.yika W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41751c50)
06-22 09:25:51.840 10896-10896/com.ilifeceo.yika E/CrashHandler: In thread: Thread[main,5,main]
                                                                 UncaughtException detected: java.lang.NoClassDefFoundError: okhttp3.MediaType
                                                                     at com.lzy.okgo.model.HttpParams.<clinit>(HttpParams.java:28)
                                                                     at com.ilifeceo.yika.biz.Http4GetConfig.execute(Http4GetConfig.java:35)
                                                                     at com.ilifeceo.yika.activity.LoginActivity.getConfig(LoginActivity.java:637)
                                                                     at com.ilifeceo.yika.activity.LoginActivity.onCreate(LoginActivity.java:161)
                                                                     at android.app.Activity.performCreate(Activity.java:5285)
```

**Comment by jeasonlzy** [comment]
看文档  [常见问题汇总](https://github.com/jeasonlzy/okhttp-OkGo/wiki/Q&A)
