### ISSUE TITLE
cookie 在持久化时遇到空指针 okgo 2.1.4

### ISSUE THREAD

**Issue by pdog18** [jeasonlzy/okhttp-OkGo#350]
java.lang.NullPointerException
	at com.lzy.okgo.cookie.store.PersistentCookieStore.saveCookie(PersistentCookieStore.java)
	at com.lzy.okgo.cookie.store.PersistentCookieStore.saveCookie(PersistentCookieStore.java)
	at com.lzy.okgo.cookie.CookieJarImpl.saveFromResponse(CookieJarImpl.java)
	at okhttp3.internal.http.HttpHeaders.receiveHeaders(HttpHeaders.java:182)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at com.lzy.okgo.interceptor.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

看不出来哪个位置是空指针啊，好苦恼

**Comment by pdog18** [comment]
糟糕是这个问题我也不能复现，看了后台信息，是一台4.4.2系统的华为低端手机上发生的

**Comment by pdog18** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.concurrent.ConcurrentHashMap.put(java.lang.Object, java.lang.Object)' on a null object reference
	at com.lzy.okgo.cookie.store.PersistentCookieStore.saveCookie(PersistentCookieStore.java)
	at com.lzy.okgo.cookie.store.PersistentCookieStore.saveCookie(PersistentCookieStore.java)
	at com.lzy.okgo.cookie.CookieJarImpl.saveFromResponse(CookieJarImpl.java)
	at okhttp3.internal.http.HttpHeaders.receiveHeaders(HttpHeaders.java:182)

这一次发生，显示有一个ConcurrentHashMap对象为空
```
   private void saveCookie(HttpUrl url, Cookie cookie, String name) {
        //内存缓存
        cookies.get(url.host()).put(name, cookie);
        //文件缓存
        SharedPreferences.Editor prefsWriter = cookiePrefs.edit();
        prefsWriter.putString(url.host(), TextUtils.join(",", cookies.get(url.host()).keySet()));
        prefsWriter.putString(COOKIE_NAME_PREFIX + name, encodeCookie(new SerializableHttpCookie(cookie)));
        prefsWriter.apply();
    }
```

感觉应该是`cookies.get(url.host()).put(name, cookie);`这一行有问题。

**Comment by pdog18** [comment]
我不知道`cookies.get(url.host())`为什么会为空？
如果是因为被请求被劫持，而被劫持的地址没有url，会出现这个`ConcurrentHashMap`为`null`的情况吗？
另外小白请教一下，如果被请求被劫持，这个地址会由`okgo`的`okhttp`来访问吗？
谢谢

**Comment by jeasonlzy** [comment]
你分析的  cookies.get(url.host())  为空是对的，可能是由于手动操作了cookie的原因吧，自己多线程操作cookie，导致异常了。。

**Comment by pdog18** [comment]
cookie 这里我只用了您的处理。。没有其他手动操作cookie的地方。
难道webview中loadurl有影响?应该不会吧

**Comment by pdog18** [comment]
```
 OkGo.init(this);
        OkGo.getInstance()
                .debug("Okgo", Level.INFO, Switchs.OKGO_LOG_ENABLE)
                .setConnectTimeout(10000)               //全局的连接超时时间 （服务器访问超时）
                .setReadTimeOut(10000)                  //全局的读取超时时间
                .setWriteTimeOut(10000)                 //全局的写入超时时间
                .setRetryCount(1)                      //全局的重试次数
                .setCacheMode(CacheMode.FIRST_CACHE_THEN_REQUEST)  //先使用缓存，不管是否存在，仍然请求网络
                .setCookieStore(new MemoryCookieStore())        //内存缓存
                .setCookieStore(new PersistentCookieStore())  //持久化缓存
                .setCertificates();    //信任所有https证书
```

整个app中与cookie有关的设置就在这里了，我将代码贴出来时发现，是我同时设置了内存缓存和持久化缓存的原因？因为我看您的代码，在持久化的同时也会在内存中存放一份。

**Comment by jeasonlzy** [comment]
同时设置没用，只有最后一个生效。

可以自己在 saveCookie 方法上加同步锁，或者使用 3.0 版本，已经加过锁了，不想换3.0的话，可以参考3.0 cookie包下的代码到2.1.4中。。改动不大。。

**Comment by pdog18** [comment]
谢谢您的回复。我尝试解决一下。
