### ISSUE TITLE
初始化okdownload ExceptionInInitializerError

### ISSUE THREAD

**Issue by melody1993** [jeasonlzy/okhttp-OkGo#370]
java.lang.ExceptionInInitializerError
                                                                             at com.lzy.okgo.db.DownloadManager.getInstance(DownloadManager.java:41)
                                                                             at com.lzy.okserver.OkDownload.<init>(OkDownload.java:66)
                                                                             at com.lzy.okserver.OkDownload.<init>(OkDownload.java:45)
                                                                             at com.lzy.okserver.OkDownload$OkDownloadHolder.<clinit>(OkDownload.java:56)
                                                                             at com.lzy.okserver.OkDownload.getInstance(OkDownload.java:52)

**Comment by ktoy1943** [comment]
我也是吖 怎么解决了?
