### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by zhengxuan666** [jeasonlzy/okhttp-OkGo#412]
`java.util.ConcurrentModificationException
at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
at com.lzy.okgo.model.Progress.bufferSpeed(Progress.java)
at com.lzy.okgo.model.Progress.changeProgress(Progress.java)
at com.lzy.okserver.download.DownloadTask.download(DownloadTask.java)
at com.lzy.okserver.download.DownloadTask.run(DownloadTask.java)
at com.lzy.okserver.task.PriorityRunnable.run(PriorityRunnable.java)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)`

3.0.4 的

**Comment by zhengxuan666** [comment]
这个情况偶发
有一批文件列表,初始化的时候检查文件是否下载过等等情况

      Progress progress = DownloadManager.getInstance().get(url);
        DownloadTask task;
        if (progress != null) {
            task = OkDownload.restore(progress);
            if (task != null) {
                //已经在列队里
                task.register(new LogDownloadListener());
                if (task.progress.status == Progress.FINISH) {
                    //已经完成  文件可能被删除了
                    task.restart();
                } else if (task.progress.status == Progress.ERROR) {
                    //任务出错
                    task.start();
                } else if (task.progress.status == Progress.LOADING) {
                    //下载中
                } else if (task.progress.status == Progress.PAUSE) {
                    //暂停
                    task.start();
                } else if (task.progress.status == Progress.WAITING) {
                    //下载等待
                } else if (task.progress.status == Progress.NONE) {
                    //无状态  待下载
                    task.start();
                }
            }
        } else {
            //从没下过
            PostRequest<File> request = OkGo.<File>post(url);
            request.headers(new HttpHeaders());
            request.params(new HttpParams());
            OkDownload.request(url, request)
                    .fileName(generator.generate(url) + ".tmp")
                    .save()
                    .register(new LogDownloadListener())
                    .start();

        }
