### ISSUE TITLE
302的请求三星手机debug模式报错

### ISSUE THREAD

**Issue by yaooort** [jeasonlzy/okhttp-OkGo#476]
再三星s6上有包含302的请求debug版本会报错，但是正式打包之后就不会，具体报错日志为

com.lzy.okgo.exception.HttpException: network error! http response code is 404 or 5xx!

at com.lzy.okgo.cache.policy.BaseCachePolicy$1.onResponse(BaseCachePolicy.java:155)

at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)

at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)

at java.lang.Thread.run(Thread.java:762)

请问这个是由于什么造成的

**Comment by ypf168326** [comment]
我出现这个错误是，连续多次调用报错了，第一次能正常拿到数据，第二次调用就抱错了。

**Comment by cccfly-bake** [comment]
同问，这个bug解决了，
