### ISSUE TITLE
unexpected end of stream

### ISSUE THREAD

**Issue by sheilazxx** [jeasonlzy/okhttp-OkGo#478]
10-09 01:38:00.185 18594-18647/com.shzx.zcyg W/System.err: java.net.ProtocolException: unexpected end of stream
10-09 01:38:00.185 18594-18647/com.shzx.zcyg W/System.err:     at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:387)
10-09 01:38:00.185 18594-18647/com.shzx.zcyg W/System.err:     at okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
10-09 01:38:00.186 18594-18647/com.shzx.zcyg W/System.err:     at java.io.InputStream.read(InputStream.java:101)
10-09 01:38:00.186 18594-18647/com.shzx.zcyg W/System.err:     at com.lzy.okgo.utils.IOUtils.write(IOUtils.java:278)
10-09 01:38:00.187 18594-18647/com.shzx.zcyg W/System.err:     at com.lzy.okgo.utils.IOUtils.toByteArray(IOUtils.java:175)
10-09 01:38:00.187 18594-18647/com.shzx.zcyg W/System.err:     at com.lzy.okgo.interceptor.HttpLoggingInterceptor.logForResponse(HttpLoggingInterceptor.java:170)
10-09 01:38:00.187 18594-18647/com.shzx.zcyg W/System.err:     at com.lzy.okgo.interceptor.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:101)
10-09 01:38:00.187 18594-18647/com.shzx.zcyg W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
10-09 01:38:00.187 18594-18647/com.shzx.zcyg W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
10-09 01:38:00.187 18594-18647/com.shzx.zcyg W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
10-09 01:38:00.187 18594-18647/com.shzx.zcyg W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
10-09 01:38:00.187 18594-18647/com.shzx.zcyg W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
10-09 01:38:00.187 18594-18647/com.shzx.zcyg W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
10-09 01:38:00.187 18594-18647/com.shzx.zcyg W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
10-09 01:38:00.187 18594-18647/com.shzx.zcyg W/System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by MickeyDaddy** [comment]
我也偶现这个问题，请问有解决办法吗
