### ISSUE TITLE
java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction

### ISSUE THREAD

**Issue by toy-lin** [jeasonlzy/okhttp-OkGo#505]
#OkGo版本是3.0.4。
#系统7.0和7.1.1都有发生，用户发生概率大概是1/1000。
#设置方法
Application#onCreate中
```
OkHttpClient.Builder b = new OkHttpClient.Builder();
        OkHttpClient client = b.connectTimeout(10, TimeUnit.SECONDS)
                .readTimeout(10 ,TimeUnit.SECONDS)
                .writeTimeout(10 ,TimeUnit.SECONDS)
                .dns(new MyDns())
                .cache(new Cache(getCacheDir(),10 * 1024 * 1024))
                .cookieJar(new CookieJarImpl(new DBCookieStoreTM(sInstance)))
                .addNetworkInterceptor(new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                if (L.DEBUG)
                    L.e("intercept",chain.toString());
                return chain.proceed(chain.request());
            }
        }).build();

        OkGo.getInstance()
                .setRetryCount(0)
                .setOkHttpClient(client)
                .init(this);
```
#DBCookieStoreTM与DBCookieStore的区别就是注释了loadCookie方法中的下面一行代码以支持多进程。
```
if (!cookies.containsKey(url.host())) return ret;
```
#Stacktrace：
```
java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
	at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:915)
	at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:398)
	at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:524)
	at com.lzy.okgo.db.BaseDao.query(BaseDao.java)
	at com.lzy.okgo.db.BaseDao.query(BaseDao.java)
	at com.xxx.xxx.module.network.DBCookieStoreTM.loadCookie(DBCookieStoreTM.java)
	at com.lzy.okgo.cookie.CookieJarImpl.loadForRequest(CookieJarImpl.java)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
```

**Comment by toy-lin** [comment]
哦。。。sorry，就是因为注释了那一行代码引起的。
