### ISSUE TITLE
总是下载出错

### ISSUE THREAD

**Issue by sundyli** [jeasonlzy/okhttp-OkGo#514]
下载6个文件，有5个出错，打印信息如下：
W/System.err: com.lzy.okgo.exception.OkGoException: breakpoint file has expired!
W/System.err:     at com.lzy.okserver.download.DownloadTask.run(Unknown Source)
W/System.err:     at com.lzy.okserver.task.PriorityRunnable.run(Unknown Source)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
E/DownloadAdapter: onError:breakpoint file has expired!

**Comment by sundyli** [comment]
问题已解决，不是库的问题，请删除此issue

**Comment by zjsa** [comment]
怎么解决的？ @
