### ISSUE TITLE
 com.lzy.okgo.exception.OkGoException: breakpoint file has expired!

### ISSUE THREAD

**Issue by zjsa** [jeasonlzy/okhttp-OkGo#574]
W/System.err: com.lzy.okgo.exception.OkGoException: breakpoint file has expired!
W/System.err:     at com.lzy.okserver.download.DownloadTask.run(DownloadTask.java:281)
W/System.err:     at com.lzy.okserver.task.PriorityRunnable.run(PriorityRunnable.java:35)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err:     at java.lang.Thread.run(Thread.java:776)

想问下这个错误，下载PDF格式的文件包的错误

**Comment by DaveBoy** [comment]
这个是你把断点下载中  下载到一半的文件删除了
