### ISSUE TITLE
java.io.EOFException: \n not found: limit=1 content=0d…

### ISSUE THREAD

**Issue by HappyImp** [jeasonlzy/okhttp-OkGo#607]
用OKGO 用 Get同时请求多个接口然后报错，不是百分百会出这问题，但经常会有部分接口报错
` java.io.EOFException: \n not found: limit=1 content=0d…`

`01-26 08:18:19.734 26481-26653/com.huaran.dfhnshop W/System.err: java.io.EOFException: \n not found: limit=1 content=0d…
01-26 08:18:19.734 26481-26653/com.huaran.dfhnshop W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
01-26 08:18:19.734 26481-26653/com.huaran.dfhnshop W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
01-26 08:18:19.734 26481-26653/com.huaran.dfhnshop W/System.err:     at okhttp3.internal.http1.Http1Codec.readHeaders(Http1Codec.java:215)
01-26 08:18:19.734 26481-26653/com.huaran.dfhnshop W/System.err:     at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:455)
01-26 08:18:19.734 26481-26653/com.huaran.dfhnshop W/System.err:     at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:425)
01-26 08:18:19.734 26481-26653/com.huaran.dfhnshop W/System.err:     at okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
01-26 08:18:19.734 26481-26653/com.huaran.dfhnshop W/System.err:     at java.io.InputStream.read(InputStream.java:101)
01-26 08:18:19.734 26481-26653/com.huaran.dfhnshop W/System.err:     at huaran.com.baseui.http.okgo.utils.IOUtils.write(IOUtils.java:264)
01-26 08:18:19.734 26481-26643/com.huaran.dfhnshop I/kyluzoi: <-- END HTTP
01-26 08:18:19.734 26481-26653/com.huaran.dfhnshop W/System.err:     at huaran.com.baseui.http.okgo.utils.IOUtils.toByteArray(IOUtils.java:161)
01-26 08:18:19.734 26481-26653/com.huaran.dfhnshop W/System.err:     at huaran.com.baseui.http.okgo.interceptor.HttpLoggingInterceptor.logForResponse(HttpLoggingInterceptor.java:138)
01-26 08:18:19.734 26481-26653/com.huaran.dfhnshop W/System.err:     at huaran.com.baseui.http.okgo.interceptor.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:85)
01-26 08:18:19.734 26481-26653/com.huaran.dfhnshop W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
01-26 08:18:19.735 26481-26653/com.huaran.dfhnshop W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
01-26 08:18:19.735 26481-26653/com.huaran.dfhnshop W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
01-26 08:18:19.735 26481-26653/com.huaran.dfhnshop W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
01-26 08:18:19.735 26481-26653/com.huaran.dfhnshop W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
01-26 08:18:19.735 26481-26653/com.huaran.dfhnshop W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-26 08:18:19.735 26481-26653/com.huaran.dfhnshop W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-26 08:18:19.735 26481-26653/com.huaran.dfhnshop W/System.err:     at java.lang.Thread.run(Thread.java:761)`

**Comment by HappyImp** [comment]
设备是Android Emulator 7.1.1

**Comment by sohow** [comment]
+1

**Comment by jyjiawohao** [comment]
+1 你们怎么解决的 这个项目好像是不维护了吧
