### ISSUE TITLE
 java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by hero0812** [jeasonlzy/okhttp-OkGo#681]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.binbinyl.bbbang, PID: 31747
                                                                     java.util.ConcurrentModificationException
                                                                         at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
                                                                         at java.util.HashMap$ValueIterator.next(HashMap.java:1470)
                                                                         at com.lzy.okserver.download.DownloadTask$2.run(DownloadTask.java:362)
                                                                         at android.os.Handler.handleCallback(Handler.java:808)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                         at android.os.Looper.loop(Looper.java:166)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:7425)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by hero0812** [comment]
android 8.0 华为设备，很正常的一个下载操作，这段代码报错了：
  private void postOnStart(final Progress progress) {
        progress.speed = 0;
        progress.status = Progress.NONE;
        updateDatabase(progress);
        HttpUtils.runOnUiThread(new Runnable() {
            @Override
            public void run() {
                for (DownloadListener listener : listeners.values()) {
                    listener.onStart(progress);
                }
            }
        });
    }

**Comment by BrokerXu** [comment]
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at com.lzy.okgo.model.Progress.a(Progress.java:127)
	at com.lzy.okgo.model.Progress.changeProgress(Progress.java:110)
	at com.lzy.okserver.a.b.a(DownloadTask.java:331)
	at com.lzy.okserver.a.b.run(DownloadTask.java:297)
	at com.lzy.okserver.task.b.run(PriorityRunnable.java:11)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by hero0812** [comment]
这个问题原因就是多线程同时对某个集合进行了修改操作，我的情况是在遍历task map的时候，ui线程进行了注册新的listener操作

**Comment by BrokerXu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
我报错的地方和你的报错的地方不一样，我的是changeProgress处报错



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    在2018年05月6日 12:20，Jiang Yu<notifications@github.com> 写道： 


这个问题原因就是多线程同时对某个集合进行了修改操作，我的情况是在遍历task map的时候，ui线程进行了注册新的listener操作

**Comment by BrokerXu** [comment]
我就是每次都会创建DownloadListener所以不会报你的那个错误，我报错的地方和你的不是一个地方，有可能你也会遇到的

**Comment by BrokerXu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
该如何解决呢，是不是要加个lock



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    在2018年05月6日 13:08，brokerxu<brokerxu@qq.com> 写道： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
我报错的地方和你的报错的地方不一样，我的是changeProgress处报错



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    在2018年05月6日 12:20，Jiang Yu<notifications@github.com> 写道： 


这个问题原因就是多线程同时对某个集合进行了修改操作，我的情况是在遍历task map的时候，ui线程进行了注册新的listener操作

**Comment by hero0812** [comment]
猜想，downloadTask调用changprogeess方法时，要遍历它的listener集合，来通知到每一个listener进度发生了变化，也就是在这个时候你的downloadtask，又注册了新的listener到集合里，引起了集合并发操作问题。解决方案1）源码的HashMap改成concurrentHashmap，看到有人提过了2）自己的代码里，注册listener的时机调整下，另外记得，unregisterlistener。个人理解，可能不到位，希望能进一步看过源码后和大家讨论

**Comment by BrokerXu** [comment]
没错，我已经这样解决了，重点是在pause()之后一定要unRegister(tag),onError之后也要unRegister(tag),否则再次开启下载操作的时候又会register新的DownloadListener。感谢你的解答，祝你工作愉快！
