### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by BrokerXu** [jeasonlzy/okhttp-OkGo#683]
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at com.lzy.okgo.model.Progress.a(Progress.java:127)
	at com.lzy.okgo.model.Progress.changeProgress(Progress.java:110)
	at com.lzy.okserver.a.b.a(DownloadTask.java:331)
	at com.lzy.okserver.a.b.run(DownloadTask.java:297)
	at com.lzy.okserver.task.b.run(PriorityRunnable.java:11)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by BrokerXu** [comment]
if (task != null) {
                    task.pause();
                    task.unRegister(progress.tag);
                    //更新UI
                    if (getView() != null)
                        getView().onPause(progress);
                }

**Comment by BrokerXu** [comment]
我已经这样解决了，重点是在pause()之后一定要unRegister(tag),onError之后也要unRegister(tag),否则再次开启下载操作的时候又会register新的DownloadListener。感谢你的解答，祝你工作愉快！
