### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by BrokerXu** [jeasonlzy/okhttp-OkGo#687]
Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:632)
	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:318)
	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:292)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:213)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:191)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:581)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:279)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at com.lzy.okgo.d.a.b(BaseDao.java:58)
	at com.lzy.okgo.d.a.<init>(BaseDao.java:50)
	at com.lzy.okgo.d.g.<init>(DownloadManager.java:37)
	at com.lzy.okgo.d.g.<init>(DownloadManager.java:34)
	at com.lzy.okgo.d.g$a.<clinit>(DownloadManager.java:45)
	... 15 more

**Comment by wudongjiang333** [comment]
我也遇到了同样的问题
