### ISSUE TITLE
解析不出来了,什么原因

### ISSUE THREAD

**Issue by lxhtiamo** [jeasonlzy/okhttp-OkGo#742]
at com.lzy.okgo.cache.policy.BaseCachePolicy$1.onResponse(BaseCachePolicy.java:163)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at com.lzy.okgo.cache.policy.BaseCachePolicy$1.onResponse(BaseCachePolicy.java:163)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)

**Comment by wadewen** [comment]
同一个问题，请问解决了吗
