### ISSUE TITLE
米4上okserver下载有问题

### ISSUE THREAD

**Issue by tankai2525** [jeasonlzy/okhttp-OkGo#758]
米4版本MIUI9 8.4.28 开发版
okserver下载有点问题

**Comment by tankai2525** [comment]
这台米4 okgo基本下可以，okdown下载不了心伤

**Comment by chengww5217** [comment]
实测在 MI 4 LTE 上面使用 okserver 可以下载。

- MIUI 版本：9 7.10.26 | 开发版
- Android 版本： 6.0.1

demo 无法下载可能是 Demo 的代码问题，或未正确授予读写权限所致。

**Comment by tankai2525** [comment]
@chengww5217 果然是权限问题
com.lzy.okgo.exception.StorageException: SDCard isn't available, please check SD card and permission: WRITE_EXTERNAL_STORAGE, and you must pay attention to Android6.0 RunTime Permissions!
    at com.lzy.okserver.download.DownloadTask.run(DownloadTask.java:264)
    at com.lzy.okserver.task.PriorityRunnable.run(PriorityRunnable.java:35)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)

但是我加了动态权限管理，这个权限获取了。我用okgo基本下载都能下，这好奇怪哈

**Comment by tankai2525** [comment]
@chengww5217  demo是正常，可以下载

**Comment by tankai2525** [comment]
@chengww5217 不好意思，原来是我路径这里的test前少了个斜杆
public static final String PATH = Environment.getExternalStorageDirectory().getAbsolutePath() +  "test";
