### ISSUE TITLE
下载文件暂停之后停留几分钟之后不能继续下载

### ISSUE THREAD

**Issue by wangzipei** [jeasonlzy/okhttp-OkGo#843]
下载文件的过程中，如果一次性下载可以成功，连续暂停和继续也是可以成功的，但是在下载过程中暂停下载，然后停留几分钟之后重新下载，就会报错，希望大佬能看下是什么问题导致的
com.lzy.okgo.exception.OkGoException: breakpoint file has expired!
at com.lzy.okserver.download.DownloadTask.run(DownloadTask.java:322)
at com.lzy.okserver.task.PriorityRunnable.run(PriorityRunnable.java:35)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)

**Comment by wangzipei** [comment]
调用的是restart方法也会出现这个提示
