### ISSUE TITLE
OkDownload无法下载大文件

### ISSUE THREAD

**Issue by shineyue** [jeasonlzy/okhttp-OkGo#903]
OKDownload下载大文件崩溃，崩溃日志如下
Process: com.lzy.demo, PID: 8202
    java.lang.OutOfMemoryError: Failed to allocate a 188269544 byte allocation with 16777216 free bytes and 157MB until OOM
        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:79)
        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:207)
        at com.lzy.okgo.interceptor.HttpLoggingInterceptor.logForResponse(HttpLoggingInterceptor.java:172)
        at com.lzy.okgo.interceptor.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:101)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
        at okhttp3.RealCall.execute(RealCall.java:69)
        at com.lzy.okgo.request.base.Request.execute(Request.java:383)
        at com.lzy.okserver.download.DownloadTask.run(DownloadTask.java:236)
        at com.lzy.okserver.task.PriorityRunnable.run(PriorityRunnable.java:35)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

**Comment by blueskky** [comment]
@shineyue 遇到同样的问题，烦问你怎么解决的？
