### ISSUE TITLE
报一个没有找到hasBody的方法。小米8手机

### ISSUE THREAD

**Issue by byte-engine-chenxiaojian** [jeasonlzy/okhttp-OkGo#925]
E/AndroidRuntime( 9506): FATAL EXCEPTION: OkHttp Dispatcher
E/AndroidRuntime( 9506): Process: com.xinzhe.hotvision, PID: 9506
E/AndroidRuntime( 9506): java.lang.NoSuchMethodError: No static method hasBody(Lokhttp3/Response;)Z in class Lokhttp3/internal/http/HttpHeaders; or its super classes (declaration of 'okhttp3.internal.http.HttpHeaders' appears in /data/app/com.xinzhe.hotvision-FWxOqTaQ-kYv3H48WOPI6g==/base.apk)
E/AndroidRuntime( 9506): 	at com.lzy.okgo.interceptor.HttpLoggingInterceptor.logForResponse(HttpLoggingInterceptor.java:166)
E/AndroidRuntime( 9506): 	at com.lzy.okgo.interceptor.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:101)
E/AndroidRuntime( 9506): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
E/AndroidRuntime( 9506): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
E/AndroidRuntime( 9506): 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
E/AndroidRuntime( 9506): 	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136)
E/AndroidRuntime( 9506): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 9506): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 9506): 	at java.lang.Thread.run(Thread.java:764)

**Comment by woshihfh0123** [comment]
+1
