### ISSUE TITLE
addCookie 空指针

### ISSUE THREAD

**Issue by woyoudianhuai** [jeasonlzy/okhttp-OkGo#95]
FATAL EXCEPTION: main
                                                                     Process: com.chiyue.business, PID: 20304
                                                                     Theme: themes:{}
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'void com.lzy.okgo.cookie.CookieJarImpl.addCookies(java.util.List)' on a null object reference
                                                                         at com.lzy.okgo.request.BaseRequest.generateCall(BaseRequest.java:398)
                                                                         at com.lzy.okgo.adapter.CacheCall.execute(CacheCall.java:80)
                                                                         at com.lzy.okgo.request.BaseRequest.execute(BaseRequest.java:438)
                                                                         at com.chiyue.business.ui.TestActvity.commitSession(TestActvity.java:109)
                                                                         at com.chiyue.business.ui.TestActvity.onClick(TestActvity.java:71)
                                                                         at android.view.View.performClick(View.java:5213)
                                                                         at android.view.View$PerformClick.run(View.java:21174)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5477)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by curtis2** [comment]
我也有这个问题。

**Comment by curtis2** [comment]
需要初始化cookie的存储方式：
OkHttpUtils.getInstance().setCookieStore(new PersistentCookieStore());

**Comment by woyoudianhuai** [comment]
先前就已经初始化了，还是不行，你是可以了？

**Comment by woyoudianhuai** [comment]
先前直觉取响应头部Session，再次带着这个请求头Session提交，Session不能持久保持

**Comment by curtis2** [comment]
我初始化以后不报空指针了，现在正在试能不能用

**Comment by woyoudianhuai** [comment]
add cookie没有问题的，是我没有init的原因
