### ISSUE TITLE
okgo-3.0.4版本

### ISSUE THREAD

**Issue by majunm** [jeasonlzy/okhttp-OkGo#951]
java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
    at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:915)
    at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:398)
    at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:542)
    at com.lzy.okgo.db.BaseDao.replace(BaseDao.java:200)
    at com.lzy.okgo.cookie.store.DBCookieStore.saveCookie(DBCookieStore.java:94)
    at com.lzy.okgo.cookie.store.DBCookieStore.saveCookie(DBCookieStore.java:77)
    at com.lzy.okgo.cookie.CookieJarImpl.saveFromResponse(CookieJarImpl.java:48)
    at okhttp3.internal.http.HttpHeaders.receiveHeaders(HttpHeaders.java:318)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:95)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at com.lzy.okgo.interceptor.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)

**Comment by weeeeeeeeeeeei** [comment]
作者已经不维护了，这个库现在一堆问题

**Comment by majunm** [comment]
> 作者已经不维护了，这个库现在一堆问题

ヾ(o′▽`o)ノ°°谢谢 项目中用呢 不好动....
